apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: dotnet-grpc-service
  labels:
    p6m.dev/app: dotnet-grpc-service
spec:
  config:
    GRPC_PORT: "8080"  # Service Port
    SERVER_PORT: "8081" # Management Port
    LOGGING_STRUCTURED: "true"
    ConnectionStrings__DefaultConnection: "Host=$(postgres_dotnet_grpc_service_db_endpoint);Port=$(postgres_dotnet_grpc_service_db_port);Database=dotnet_grpc_service_db;Username=$(postgres_dotnet_grpc_service_db_username);Password=$(postgres_dotnet_grpc_service_db_password);sslmode=require"
  resources: 
    postgres:
      - name: dotnet-grpc-service
  deployment:
    image: dotnet-grpc-service-server:latest
    ports:
      - protocol: grpc
        port: 8080
      - protocol: http
        port: 8081
    readinessProbe:
      port: 8081
      path: /health
  networking:
    inbound:
      services:
        - name: dotnet-grpc-domain-gateway
          namespace: dotnet-grpc-domain-gateway
          port: 8080